version: '3.3'
services:
  paper-docs:
    image: registry.gitlab.com/minidigger/paper-docs:latest
    networks:
      - web
    labels:
      - "traefik.backend=paper-docs"
      - "traefik.frontend.rule=Host:paper-docs.minidigger.me"

networks:
  web:
    external:
      name: global_bridge
